#PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: idsmobilecoreapi-pv
  labels:
    type: local
    app: idsmobilecoreapi
spec:
  storageClassName: manual
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/oodata/"
---
#PersistentVolumeClaim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: idsmobilecoreapi-pvc
  labels:
    app: idsmobilecoreapi
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500M
---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: idsmobilecoreapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idsmobilecoreapi
  template:
    metadata:
      labels:
        app: idsmobilecoreapi
    spec:
      containers:
      - name: idsmobilecoreapi
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /app
            name: idsmobilecoreapi-data
      volumes:
        - name: idsmobilecoreapi-data
          persistentVolumeClaim:
            claimName: idsmobilecoreapi-pvc
---
apiVersion: v1
kind: Service
metadata:
    name: idsmobilecoreapi
spec:
  externalIPs:
  -  192.168.1.110
  ports:
    - name: http-port
      port: 80
      targetPort: 80
  selector:
    app: idsmobilecoreapi
  type: LoadBalancer
